place_travel: list[str]=["新疆","大理","周庄","三亚","苏州"]
print(place_travel)
print(sorted(place_travel))
print(place_travel)
print(sorted(place_travel,reverse=True))
place_travel.reverse()
print(place_travel)
place_travel.reverse()
print(place_travel)
place_travel.sort()
print(place_travel)
place_travel.sort(reverse=True)
print(place_travel)
